TARGET = iphone:clang:latest:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = CamRotateiOS78
CamRotateiOS78_FILES = Tweak.xm
CamRotateiOS78_FRAMEWORKS = UIKit
CamRotateiOS78_EXTRA_FRAMEWORKS = CydiaSubstrate
CamRotateiOS78_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/library.mk
