GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

TWEAK_NAME = CamRotateiOS7
CamRotateiOS7_FILES = Tweak.xm
CamRotateiOS7_FRAMEWORKS = UIKit
CamRotateiOS7_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/tweak.mk
