GO_EASY_ON_ME = 1
SDKVERSION = 8.0
ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = CamRotateiOS8
CamRotateiOS8_FILES = Tweak.xm
CamRotateiOS8_FRAMEWORKS = UIKit
CamRotateiOS8_LIBRARIES = substrate
CamRotateiOS8_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/library.mk
