GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

TWEAK_NAME = CamRotateiOS8
CamRotateiOS8_FILES = Tweak.xm
CamRotateiOS8_FRAMEWORKS = UIKit
CamRotateiOS8_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/tweak.mk
