TARGET = iphone:clang:latest:9.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = CamRotateiOS910
CamRotateiOS910_FILES = Tweak.xm
CamRotateiOS910_FRAMEWORKS = UIKit
CamRotateiOS910_EXTRA_FRAMEWORKS = CydiaSubstrate
CamRotateiOS910_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/library.mk
