GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

TWEAK_NAME = CamRotateiOS9
CamRotateiOS9_FILES = Tweak.xm
CamRotateiOS9_FRAMEWORKS = UIKit
CamRotateiOS9_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/tweak.mk
