GO_EASY_ON_ME = 1
ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = CamRotateiOS9
CamRotateiOS9_FILES = Tweak.xm
CamRotateiOS9_FRAMEWORKS = UIKit
CamRotateiOS9_LIBRARIES = substrate
CamRotateiOS9_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/library.mk
