GO_EASY_ON_ME = 1
SDKVERSION = 6.0
ARCHS = armv7

include ../theos/makefiles/common.mk

TWEAK_NAME = CamRotateiOS56
CamRotateiOS56_FILES = Tweak.xm
CamRotateiOS56_FRAMEWORKS = UIKit
CamRotateiOS56_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/tweak.mk
