TARGET = iphone:clang:latest:5.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = CamRotateiOS56
CamRotateiOS56_FILES = Tweak.xm
CamRotateiOS56_FRAMEWORKS = UIKit
CamRotateiOS56_EXTRA_FRAMEWORKS = CydiaSubstrate
CamRotateiOS56_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/library.mk
