GO_EASY_ON_ME = 1
SDKVERSION = 6.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = CamRotateiOS56
CamRotateiOS56_FILES = Tweak.xm
CamRotateiOS56_FRAMEWORKS = UIKit
CamRotateiOS56_LIBRARIES = substrate
CamRotateiOS56_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/library.mk
