GO_EASY_ON_ME = 1
ARCHS = armv7s arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = CamRotateiOS10
CamRotateiOS10_FILES = Tweak.xm
CamRotateiOS10_FRAMEWORKS = UIKit
CamRotateiOS10_INSTALL_PATH = /Library/Application Support/CamRotate

include $(THEOS_MAKE_PATH)/tweak.mk
